version: '3.8'
services:
  filedownloadbackend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak

  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: download
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL:-http://localhost:8090}
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
    ports:
      - "8090:8080"
    command: start-dev
    volumes:
      - ./keycloak/leno-realm.json:/opt/keycloak/data/import/realm.json:ro

volumes:
  postgres_data:
  keycloak_data:
